### ISSUE TITLE
Organize the client side javascript into folders by entrypoint

### ISSUE THREAD

**Issue by chrisuehlinger** [janpaul123/paperprograms#2]
This project's use of webpack's multi-entry point feature is awesome. I think organizing each entry point's modules into a folder (i.e. a `/camera` folder containg all the code used in `entry-camera.js`) would help make it clear which code is used on which page. Also, it might be a good idea to pull all the JS code from the `/www` directory into `/client` just so that all the JS code is in one place.

**Comment by janpaul123** [comment]
#6
