### ISSUE TITLE
Brittle color detection

### ISSUE THREAD

**Issue by jongold** [janpaul123/paperprograms#9]
Anyone else hung up on getting consistent dot detection? No matter what lighting conditions & webcam settings I try I'm recalibrating every few minutes :(

**Comment by janpaul123** [comment]
Yeah it's pretty bad right now. Help would be much appreciated. There are some more ideas here: https://github.com/janpaul123/paperprograms/issues/1

**Comment by janpaul123** [comment]
This should be a lot better now. Feel free to reopen and add more details if you're still having issues! 👍
